services:
  redis-server:
    image: redis:latest
    container_name: node-redis-server
    ports:
      - "6379:6379"
    networks:
      - node_redis_network

networks:
  node_redis_network:
    external: true